// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt0RbuEgKpiMQWp-LVHh9JMlT1JckGgPU',
    appId: '1:150589550145:web:6a39a0202793118342a0c0',
    messagingSenderId: '150589550145',
    projectId: 'navtour-281fa',
    authDomain: 'navtour-281fa.firebaseapp.com',
    storageBucket: 'navtour-281fa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAfQUD3LMAFsIOE9cPu5s4Elred9GwXKE',
    appId: '1:150589550145:android:d15d6fbe9055d54642a0c0',
    messagingSenderId: '150589550145',
    projectId: 'navtour-281fa',
    storageBucket: 'navtour-281fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGO_leu3OQlKN_RbkBtHJbe8MJ1eo8MKE',
    appId: '1:150589550145:ios:09345c8efdacb29d42a0c0',
    messagingSenderId: '150589550145',
    projectId: 'navtour-281fa',
    storageBucket: 'navtour-281fa.appspot.com',
    iosBundleId: 'com.example.navtour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGO_leu3OQlKN_RbkBtHJbe8MJ1eo8MKE',
    appId: '1:150589550145:ios:7a29cbfc7d49be1642a0c0',
    messagingSenderId: '150589550145',
    projectId: 'navtour-281fa',
    storageBucket: 'navtour-281fa.appspot.com',
    iosBundleId: 'com.example.navtour.RunnerTests',
  );
}
